### ISSUE TITLE
Missing 2d_bbox folder while converting to KITTI format

### ISSUE THREAD

**Issue by abhi1kumar** [ut-amrl/coda-models#10]
Hi @artzha
Thank you for releasing the coda-models scripts. This issue is a followup of [coda-devkit#20](https://github.com/ut-amrl/coda-devkit/issues/20). The following error showed up when I ran the CODa converter: `python tools/create_data.py coda` command:

```bash
Start converting ...
  0%|                                                                     | 0/19511 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/abhinav/anaconda3/envs/coda11_3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/abhinav/project/coda-models/tools/data_converter/coda_converter.py", line 358, in convert_one
    self.save_label(traj, cam_id, frame_idx, file_idx)
  File "/home/abhinav/project/coda-models/tools/data_converter/coda_converter.py", line 482, in save_label
    twod_anno_dict = np.loadtxt(twod_anno_path, dtype=int).reshape(-1, 6)
  File "/home/abhinav/anaconda3/envs/coda11_3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/abhinav/anaconda3/envs/coda11_3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/abhinav/anaconda3/envs/coda11_3/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/abhinav/anaconda3/envs/coda11_3/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: ./data/coda_original_format/2d_bbox/cam0/0/2d_bbox_cam0_0_451.txt not found.
```

The converter.py file [looks](https://github.com/ut-amrl/coda-models/blob/3590dff72f119f6a731b5c56fb5fed63f34d4784/tools/data_converter/coda_converter.py#L479-L482) for the 2D annotations file, but could not find inside the `2d_bbox` folder. 

I appreciate you [letting me know](https://github.com/ut-amrl/coda-devkit/issues/20#issuecomment-2127358586) that you are able to share this `2d_bbox` folder via a link. 

Would it be possible to share the `2d_bbox` folder here? This would allow me to download the folder and use for our research. I once again thank you for your timely help and assistance.

**Comment by artzha** [comment]
Hi @abhi1kumar, Thanks for raising this issue! We have uploaded a zip file containing the 2d_bbox folder to our TACC data distribution server. You may [download the zip file from this url](https://web.corral.tacc.utexas.edu/texasrobotics/web_CODa/CODa_models/). Once unzipping, you should see a folder 2d_bbox with the following directory structure:

```
2d_bbox
|_cam0
        |_{seq}
             |_2d_bbox_cam0_{seq}_{frame}.txt
```

**Comment by abhi1kumar** [comment]
Hi @artzha 
Thank you once again for sharing. Unfortunately, I still encounter the same error

 ```bashrc
 ./data/coda_original_format/2d_bbox/cam0/0/2d_bbox_cam0_0_451.txt not found.
 ```

I quickly counted the number of files inside the `cam0` folder with the command `find * -type f | wc -l`. 
![Screenshot from 2024-05-23 13-48-33](https://github.com/ut-amrl/coda-models/assets/43099708/7d96422d-bea5-4490-aa4e-671f80bd2b18)


It reports a total of 6592 files. My guess is that the converter script expects some more `2d_bbox` text files which it can not find in the current `2d_bbox` upload. 

Would you mind double check if there are only 6592 `2d_bbox` txt files needed for conversion.

**Comment by artzha** [comment]
I uploaded a more updated version of 2d_bbox.zip file to the same location. I haven't checked each file manually, but I can confirm it contains same number of 2d_bbox as 3d_bbox files. You should see 27876 files under each label directory.

**Comment by abhi1kumar** [comment]
> I uploaded a more updated version of 2d_bbox.zip file to the same location. I haven't checked each file manually, but I can confirm it contains same number of 2d_bbox as 3d_bbox files. You should see 27876 files under each label directory.

Thank you once again. The error is fixed now. I deeply appreciate your timely help and assistance with your awesome CODa dataset.
